highlighter: pygments
timezone: Europe/London
exclude: [README.md]

# Site settings
title: William Mayor's Blog
email: mail@williammayor.co.uk
description: William Mayor's personal blog.
url: "http://www.williammayor.co.uk"
twitter_username: WilliamMayor
github_username:  WilliamMayor

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Serve setting
host: 0.0.0.0
